# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: PierMobayed.CpuThermometar
PackageVersion: 0.1.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: cpu-thermometar.exe
    PortableCommandAlias: cpu-thermometar
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/PierMobayed/cpu-thermometar-windows/releases/download/v0.1.0/cpu-thermometar-windows.zip
    InstallerSha256: 604E55F2BC9B11B9EC7B297BBDC3E2E5A9866C35A9A36CAF83D7F1D0FB87B96A
    Dependencies:
      PackageDependencies:
        - PackageIdentifier: namazso.PawnIO
        - PackageIdentifier: OpenJS.NodeJS.LTS
ManifestType: installer
ManifestVersion: 1.12.0
